# -*- coding: utf-8 -*-
"""main.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/18PZGTkxTx5vvLvC5bVOpIVPPN2lM6o8Q
"""



########## API Building Last Edit ##########################


from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional
from sentence_transformers import SentenceTransformer, util
import logging
import time

app = FastAPI()

# ================== Logging ==================
logging.basicConfig(level=logging.INFO)

# ================== Model ==================
model = SentenceTransformer('BAAI/bge-m3')

# ================== Schemas ==================
class MentorInput(BaseModel):
    mentor_id: int
    job_title: Optional[str] = ""
    years_experience: Optional[int] = 0
    rating: float
    location: Optional[str] = ""
    skills: List[str]
    experiences: Optional[List[str]] = None


class RecommendRequest(BaseModel):
    student_id: str
    skills: List[str]
    experiences: List[str]
    mentors_data: List[MentorInput]


class MentorResult(BaseModel):
    mentor_id: int
    score: float


class RecommendResponse(BaseModel):
    student_id: str
    top_mentors: List[MentorResult]


# ================== Health Check ==================
@app.get("/")
def health_check():
    return {"status": "running"}


# ================== Warmup ==================
@app.get("/warmup")
def warmup():
    model.encode("test")
    return {"status": "model warmed up"}


# ================== Endpoint ==================
@app.post("/recommend", response_model=RecommendResponse)
def recommend(request: RecommendRequest):

    start_time = time.time()
    logging.info(f"Request received for student_id={request.student_id}")

    try:
        # ================== Validation ==================
        if not request.skills and not request.experiences:
            raise HTTPException(status_code=400, detail="Student data is empty")

        if not request.mentors_data:
            raise HTTPException(status_code=400, detail="No mentors provided")

        if len(request.mentors_data) > 100:
            raise HTTPException(status_code=400, detail="Too many mentors (max 100)")

        # ================== Prepare Text ==================
        student_text = " ".join(request.skills + request.experiences)

        mentor_texts = [
            (m.job_title or "") + " " +
            " ".join(m.skills) + " " +
            " ".join(m.experiences or [])
            for m in request.mentors_data
        ]

        # ================== Embeddings ==================
        student_emb = model.encode(student_text, convert_to_tensor=True, normalize_embeddings=True)
        mentor_embs = model.encode(mentor_texts, convert_to_tensor=True, normalize_embeddings=True)

        similarities = util.cos_sim(student_emb, mentor_embs)[0]

        # ================== Scoring ==================
        results = []
        for i, mentor in enumerate(request.mentors_data):
            sim = similarities[i].item()
            score = round((sim * 0.8 + (mentor.rating / 5) * 0.2) * 100, 2)

            results.append(
                MentorResult(
                    mentor_id=mentor.mentor_id,
                    score=score
                )
            )

        results.sort(key=lambda x: x.score, reverse=True)

        # ================== Response ==================
        return {
            "student_id": request.student_id,
            "top_mentors": results[:3]
        }

    except HTTPException as e:
        raise e

    except Exception as e:
        logging.error(str(e))
        raise HTTPException(status_code=500, detail=str(e))
    
import uvicorn

if __name__ == "__main__":
      uvicorn.run(app, host="0.0.0.0", port=7860)