// <auto-generated />
using System;
using InternWay;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternWay.Migrations
{
    [DbContext(typeof(InternShipWayDB))]
    partial class InternShipWayDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternWay.Models.PaymentSystem.MentorWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.Property<decimal>("PendingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MentorId")
                        .IsUnique();

                    b.ToTable("MentorWallets", "PaymentSystem");
                });

            modelBuilder.Entity("InternWay.Models.PaymentSystem.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefundStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments", "PaymentSystem");
                });

            modelBuilder.Entity("InternWay.Models.PaymentSystem.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions", "PaymentSystem");
                });

            modelBuilder.Entity("InternWay.Models.auth_schema.Notification", b =>
                {
                    b.Property<int>("Notification_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notification_Id"));

                    b.Property<DateTime>("Create_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Is_Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Message_Text");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Notification_Id")
                        .HasName("Notification_Id_PK");

                    b.HasIndex("User_Id");

                    b.ToTable("Notifications", "auth");
                });

            modelBuilder.Entity("InternWay.Models.auth_schema.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokeOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("InternWay.Models.auth_schema.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Create_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("User_id_PK");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Application", b =>
                {
                    b.Property<int>("Application_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Application_Id"));

                    b.Property<int>("Internship_Id")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("applied_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Application_Id")
                        .HasName("Application_Id_PK");

                    b.HasIndex("Internship_Id");

                    b.HasIndex("Student_Id", "Internship_Id")
                        .IsUnique();

                    b.ToTable("Applications", "company");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Company", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("company_id"));

                    b.Property<string>("Facebook")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Instagram")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Twitter")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("foundedYear")
                        .HasColumnType("int");

                    b.Property<string>("industry")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("officeAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("website")
                        .HasColumnType("varchar(255)");

                    b.HasKey("company_id")
                        .HasName("company_id_PK");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Companies", "company");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Internship", b =>
                {
                    b.Property<int>("Internship_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Internship_Id"));

                    b.Property<DateTime>("Create_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Revoked_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Update_At")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("application_deadline")
                        .HasColumnType("date");

                    b.Property<int>("company_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duration_months")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("location_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paid_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("priceInternship")
                        .HasColumnType("float");

                    b.Property<string>("requirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Open");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Internship_Id")
                        .HasName("Internship_Id_PK");

                    b.HasIndex("company_id");

                    b.ToTable("Internships", "company");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Internship_Skills", b =>
                {
                    b.Property<int>("Internship_Id")
                        .HasColumnType("int");

                    b.Property<int>("Skill_Id")
                        .HasColumnType("int");

                    b.HasKey("Internship_Id", "Skill_Id")
                        .HasName("Internship_Skills_PK");

                    b.HasIndex("Skill_Id");

                    b.ToTable("Internship_Skills", "company");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Skill", b =>
                {
                    b.Property<int>("Skill_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Skill_Id"));

                    b.Property<string>("Skill_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Skill_Id")
                        .HasName("Skill_Id_PK");

                    b.HasIndex("Skill_Name")
                        .IsUnique();

                    b.ToTable("Skills", "company");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor", b =>
                {
                    b.Property<int>("Mentor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mentor_Id"));

                    b.Property<double>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("CountReviewers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CvFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvPublicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job_Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Linkedin")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Years_Experience")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Mentor_Id")
                        .HasName("Mentor_Id_PK");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Mentors", "mentor");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor_Availability", b =>
                {
                    b.Property<int>("Slot_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Slot_Id"));

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<bool>("is_booked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("mentor_id")
                        .HasColumnType("int");

                    b.Property<string>("paid_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("priceSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("session_link")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time");

                    b.HasKey("Slot_Id")
                        .HasName("Slot_Id_PK");

                    b.HasIndex("mentor_id", "date", "start_time")
                        .IsUnique();

                    b.ToTable("Mentor_Availabilities", "mentor");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor_Experience", b =>
                {
                    b.Property<int>("mentor_id")
                        .HasColumnType("int");

                    b.Property<int>("expertise_Id")
                        .HasColumnType("int");

                    b.HasKey("mentor_id", "expertise_Id")
                        .HasName("Mentor_Experiences_PK");

                    b.HasIndex("expertise_Id");

                    b.ToTable("Mentor_Experiences", "mentor");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor_Skill", b =>
                {
                    b.Property<int>("mentor_id")
                        .HasColumnType("int");

                    b.Property<int>("skill_Id")
                        .HasColumnType("int");

                    b.HasKey("mentor_id", "skill_Id")
                        .HasName("Mentor_Skills_PK");

                    b.HasIndex("skill_Id");

                    b.ToTable("Mentor_Skills", "mentor");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentorship_Session", b =>
                {
                    b.Property<int>("session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("session_id"));

                    b.Property<DateTime?>("MentorJoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StudentJoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("slot_id")
                        .HasColumnType("int");

                    b.Property<string>("status_session")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("student_id")
                        .HasColumnType("int");

                    b.Property<int>("topic")
                        .HasColumnType("int");

                    b.HasKey("session_id")
                        .HasName("Session_Id_PK");

                    b.HasIndex("slot_id");

                    b.HasIndex("student_id");

                    b.ToTable("Mentorship_Sessions", "mentor");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id", "StudentId", "SessionId", "MentorId")
                        .HasName("Review_Id_PK");

                    b.HasIndex("MentorId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("Reviews", "mentor");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Experience", b =>
                {
                    b.Property<int>("expertiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("expertiseId"));

                    b.Property<string>("companyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("startDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("expertiseId")
                        .HasName("Experience_Id_PK");

                    b.ToTable("Experiences", "student");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student", b =>
                {
                    b.Property<int>("Student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_Id"));

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CvFileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CvPublicID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Degree")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Graduation_Year")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleteAccount")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumCancelSession")
                        .HasColumnType("int");

                    b.Property<int>("NumReschaduleSession")
                        .HasColumnType("int");

                    b.Property<int>("SessionLimitedId")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("location")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Student_Id")
                        .HasName("Student_Id_PK");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Students", "student");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student_Experience", b =>
                {
                    b.Property<int>("student_id")
                        .HasColumnType("int");

                    b.Property<int>("expertise_Id")
                        .HasColumnType("int");

                    b.HasKey("student_id", "expertise_Id")
                        .HasName("Student_Experiences_PK");

                    b.HasIndex("expertise_Id");

                    b.ToTable("Student_Experiences", "student");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student_Session_limitation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BookingBlockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<int>("CancelCountTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("LastHourCancellationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("LastHourRescheduleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly>("LastResetDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CAST(GETUTCDATE() AS DATE)");

                    b.Property<int>("RescheduleCountTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id", "StudentId")
                        .HasName("Pk_Student_Session_limitation");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Student_Session_limitations", "student");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student_Skills", b =>
                {
                    b.Property<int>("student_id")
                        .HasColumnType("int");

                    b.Property<int>("skill_id")
                        .HasColumnType("int");

                    b.HasKey("student_id", "skill_id")
                        .HasName("Student_Skills_PK");

                    b.HasIndex("skill_id");

                    b.ToTable("Student_Skills", "student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InternWay.Models.PaymentSystem.MentorWallet", b =>
                {
                    b.HasOne("InternWay.Models.mentor_schema.Mentor", "Mentor")
                        .WithOne("Wallet")
                        .HasForeignKey("InternWay.Models.PaymentSystem.MentorWallet", "MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("InternWay.Models.PaymentSystem.Payment", b =>
                {
                    b.HasOne("InternWay.Models.mentor_schema.Mentorship_Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternWay.Models.student_schema.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternWay.Models.auth_schema.Notification", b =>
                {
                    b.HasOne("InternWay.Models.auth_schema.User", "user")
                        .WithMany("notifications")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Notification_FK");

                    b.Navigation("user");
                });

            modelBuilder.Entity("InternWay.Models.auth_schema.RefreshToken", b =>
                {
                    b.HasOne("InternWay.Models.auth_schema.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Application", b =>
                {
                    b.HasOne("InternWay.Models.company_schema.Internship", "internship")
                        .WithMany("applications")
                        .HasForeignKey("Internship_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Internship_Application_FK");

                    b.HasOne("InternWay.Models.student_schema.Student", "Student")
                        .WithMany("applications")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Student_Application_FK");

                    b.Navigation("Student");

                    b.Navigation("internship");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Company", b =>
                {
                    b.HasOne("InternWay.Models.auth_schema.User", "User")
                        .WithOne("Company")
                        .HasForeignKey("InternWay.Models.company_schema.Company", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Company_FK");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Internship", b =>
                {
                    b.HasOne("InternWay.Models.company_schema.Company", "company")
                        .WithMany("internships")
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("company_Internship_FK");

                    b.Navigation("company");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Internship_Skills", b =>
                {
                    b.HasOne("InternWay.Models.company_schema.Internship", "Internship")
                        .WithMany("Internship_Skills")
                        .HasForeignKey("Internship_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternWay.Models.company_schema.Skill", "Skill")
                        .WithMany("Internship_Skills")
                        .HasForeignKey("Skill_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Internship");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor", b =>
                {
                    b.HasOne("InternWay.Models.auth_schema.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("InternWay.Models.mentor_schema.Mentor", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Mentor_FK");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor_Availability", b =>
                {
                    b.HasOne("InternWay.Models.mentor_schema.Mentor", "Mentor")
                        .WithMany("mentor_Availabilities")
                        .HasForeignKey("mentor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Mentor_Mentor_Availability_FK");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor_Experience", b =>
                {
                    b.HasOne("InternWay.Models.student_schema.Experience", "Experience")
                        .WithMany("mentor_Experiences")
                        .HasForeignKey("expertise_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternWay.Models.mentor_schema.Mentor", "mentor")
                        .WithMany("Mentor_Experiences")
                        .HasForeignKey("mentor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("mentor");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor_Skill", b =>
                {
                    b.HasOne("InternWay.Models.mentor_schema.Mentor", "mentor")
                        .WithMany("Mentor_Skills")
                        .HasForeignKey("mentor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternWay.Models.company_schema.Skill", "skill")
                        .WithMany("mentor_Skills")
                        .HasForeignKey("skill_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mentor");

                    b.Navigation("skill");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentorship_Session", b =>
                {
                    b.HasOne("InternWay.Models.mentor_schema.Mentor_Availability", "mentor_availability")
                        .WithMany("mentorship_Session")
                        .HasForeignKey("slot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mentor_availability_Mentorship_Session_FK");

                    b.HasOne("InternWay.Models.student_schema.Student", "student")
                        .WithMany("mentorship_Sessions")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_Mentorship_Session_FK");

                    b.Navigation("mentor_availability");

                    b.Navigation("student");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Review", b =>
                {
                    b.HasOne("InternWay.Models.mentor_schema.Mentor", "mentor")
                        .WithMany("Reviews")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternWay.Models.mentor_schema.Mentorship_Session", "session")
                        .WithOne("review")
                        .HasForeignKey("InternWay.Models.mentor_schema.Review", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternWay.Models.student_schema.Student", "student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mentor");

                    b.Navigation("session");

                    b.Navigation("student");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student", b =>
                {
                    b.HasOne("InternWay.Models.auth_schema.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("InternWay.Models.student_schema.Student", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Student_FK");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student_Experience", b =>
                {
                    b.HasOne("InternWay.Models.student_schema.Experience", "Experience")
                        .WithMany("student_Experiences")
                        .HasForeignKey("expertise_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternWay.Models.student_schema.Student", "Student")
                        .WithMany("Student_Experiences")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student_Session_limitation", b =>
                {
                    b.HasOne("InternWay.Models.student_schema.Student", "Student")
                        .WithOne("Session_Limitation")
                        .HasForeignKey("InternWay.Models.student_schema.Student_Session_limitation", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student_Skills", b =>
                {
                    b.HasOne("InternWay.Models.company_schema.Skill", "Skill")
                        .WithMany("Student_Skills")
                        .HasForeignKey("skill_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternWay.Models.student_schema.Student", "Student")
                        .WithMany("Student_Skills")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("InternWay.Models.auth_schema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("InternWay.Models.auth_schema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternWay.Models.auth_schema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("InternWay.Models.auth_schema.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InternWay.Models.auth_schema.User", b =>
                {
                    b.Navigation("Company")
                        .IsRequired();

                    b.Navigation("Mentor")
                        .IsRequired();

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("notifications");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Company", b =>
                {
                    b.Navigation("internships");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Internship", b =>
                {
                    b.Navigation("Internship_Skills");

                    b.Navigation("applications");
                });

            modelBuilder.Entity("InternWay.Models.company_schema.Skill", b =>
                {
                    b.Navigation("Internship_Skills");

                    b.Navigation("Student_Skills");

                    b.Navigation("mentor_Skills");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor", b =>
                {
                    b.Navigation("Mentor_Experiences");

                    b.Navigation("Mentor_Skills");

                    b.Navigation("Reviews");

                    b.Navigation("Wallet")
                        .IsRequired();

                    b.Navigation("mentor_Availabilities");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentor_Availability", b =>
                {
                    b.Navigation("mentorship_Session");
                });

            modelBuilder.Entity("InternWay.Models.mentor_schema.Mentorship_Session", b =>
                {
                    b.Navigation("review");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Experience", b =>
                {
                    b.Navigation("mentor_Experiences");

                    b.Navigation("student_Experiences");
                });

            modelBuilder.Entity("InternWay.Models.student_schema.Student", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Session_Limitation");

                    b.Navigation("Student_Experiences");

                    b.Navigation("Student_Skills");

                    b.Navigation("applications");

                    b.Navigation("mentorship_Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
